services:
  postgres:
    image: postgres:18
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ai_food_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7.2-alpine
    container_name: redis_server
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 123456

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:

# docker start postgres_db
